name: test

on:
  push:
    branches: [main] # on pushes TO main
  pull_request:
    branches: [main] # on pull requests AGAINST main

permissions:
  contents: read

# cancel CI runs when a new commit is pushed to any branch except main
concurrency:
  group: "test-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build against the two latest releases, to match golang's release
        # policy: https://go.dev/doc/devel/release#policy
        go-version:
        - 'stable'
        - 'oldstable'

    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: setup
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: ${{matrix.go-version}}

    - name: test
      run: make testci
      env:
        GITHUB_TOKEN: ${{ secrets.GHAVM_GITHUB_TOKEN }}

    - name: report code coverage
      uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
      if: ${{ matrix.go-version == 'stable' }}
